apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_USER: ZWNvbXVzZXI=
  DB_PASSWORD: ZWNvbXBhc3N3b3Jk
  DB_NAME: ZWNvbWRi
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded value for "rootpassword"
